import Link from "next/link";
import Image from "next/image";
import { PCDAtlas } from "./types";
import { fetchAtlas } from "./lib/atlas";
import { GnnDiagram } from "./components/GnnDiagram";
import { LiveStats } from "./components/LiveStats";

export const dynamic = "force-dynamic";

// ── Nav ─────────────────────────────────────────────────────────────────────
function NavBar() {
  return (
    <nav className="fixed top-0 left-0 right-0 z-50 border-b"
         style={{ background: "var(--bg)", borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 flex items-center h-10 gap-6 text-xs">
        <span className="font-mono font-bold tracking-widest text-[11px]"
              style={{ color: "var(--accent)" }}>PCD</span>
        <span style={{ color: "var(--border)" }}>|</span>
        <span className="font-medium" style={{ color: "var(--text-secondary)" }}>
          Pharmacological Chaperone Database
        </span>
        <div className="ml-auto flex items-center gap-5 text-[11px]">
          <a href="#methodology" className="nav-link">Methodology</a>
          <a href="#database" className="nav-link">Browse</a>
          <a href="#about" className="nav-link">About</a>
          <Link href="/abstract" className="nav-link">Abstract</Link>
          <Link href="/database"
            className="px-2.5 py-1 font-semibold border"
            style={{ borderColor: "var(--border-mid)", color: "var(--text-secondary)", borderRadius: "2px" }}>
            Full Database
          </Link>
        </div>
      </div>
    </nav>
  );
}

// ── Database identity header ─────────────────────────────────────────────────
function IdentityHeader({ data }: { data: PCDAtlas }) {
  const avgDrug = data.entries.reduce((s, e) => s + (e.pocket?.fpocket_druggability ?? 0), 0) / data.entries.length;
  const diseases = new Set(data.entries.map(e => e.metadata.disease)).size;
  const total = data.proteome_targets?.total_clinvar_pathogenic_missense ?? 178597;

  return (
    <section className="border-b" style={{ borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 py-8">

        {/* Top row — identity + quick-access buttons */}
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-6 mb-6">
          <div>
            <div className="flex items-center gap-2 mb-2">
              <span className="font-mono font-bold text-[10px] px-1.5 py-0.5 border"
                    style={{ color: "var(--accent)", borderColor: "var(--accent-border)", background: "var(--accent-dim)" }}>
                PCD
              </span>
              <span className="text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>
                v{data.version} · S.Y.A.L.I.S Labs · ClinVar-derived · AlphaFold2
              </span>
            </div>
            <h1 className="text-xl font-bold leading-snug" style={{ color: "var(--text-primary)" }}>
              Pharmacological Chaperone Database
            </h1>
            <p className="text-xs mt-1.5 max-w-xl leading-5" style={{ color: "var(--text-secondary)" }}>
              Proteome-scale computational database of de novo pharmacological chaperones
              for pathogenic protein misfolding variants, generated by the REFOLD pipeline.
            </p>
            <div className="flex flex-wrap gap-3 mt-3">
              <Link href="/database"
                className="px-3 py-1.5 text-xs font-semibold border transition-colors"
                style={{ background: "var(--accent)", borderColor: "var(--accent)", color: "#fff", borderRadius: "2px" }}>
                Browse Entries
              </Link>
              <a href="#methodology"
                className="px-3 py-1.5 text-xs font-semibold border transition-colors"
                style={{ borderColor: "var(--border-mid)", color: "var(--text-secondary)", borderRadius: "2px" }}>
                Methodology
              </a>
              <Link href="/abstract"
                className="px-3 py-1.5 text-xs font-semibold border transition-colors"
                style={{ borderColor: "var(--border-mid)", color: "var(--text-secondary)", borderRadius: "2px" }}>
                Conference Abstract
              </Link>
            </div>
          </div>

          {/* Live statistics panel */}
          <div className="shrink-0 w-full sm:w-auto">
            <LiveStats
              initialEntries={data.total_entries}
              initialAvgDrug={avgDrug}
              initialDiseases={diseases}
              initialTotal={total}
            />
          </div>
        </div>

        {/* Build date + citation line */}
        <div className="border-t pt-3 flex flex-wrap gap-6 text-[11px] font-mono"
             style={{ borderColor: "var(--border)", color: "var(--text-muted)" }}>
          <span>Build date: <span style={{ color: "var(--text-secondary)" }}>{data.build_date}</span></span>
          <span>Total entries: <span style={{ color: "var(--text-secondary)" }}>{data.total_entries.toLocaleString()}</span></span>
          <span>Diseases covered: <span style={{ color: "var(--text-secondary)" }}>{diseases}</span></span>
          <span>Avg. druggability: <span style={{ color: "var(--text-secondary)" }}>{avgDrug.toFixed(3)}</span></span>
        </div>
      </div>
    </section>
  );
}

// ── Scientific background ────────────────────────────────────────────────────
function BackgroundSection() {
  return (
    <section className="border-b" style={{ borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 py-8 grid lg:grid-cols-[1fr_440px] gap-10 items-start">

        <div className="space-y-4">
          <div className="section-label">Scientific Background</div>
          <h2 className="text-base font-bold" style={{ color: "var(--text-primary)" }}>
            Protein Misfolding &amp; the Pharmacological Chaperone Gap
          </h2>
          <div className="space-y-3 text-xs leading-6" style={{ color: "var(--text-secondary)" }}>
            <p>
              40–60% of pathogenic missense variants cause disease not by disrupting a protein&apos;s
              active site, but by triggering premature proteasomal degradation of the misfolded
              intermediate before it can reach its functional destination. The endoplasmic reticulum
              quality-control machinery flags structurally aberrant conformers and routes them for
              degradation via the ubiquitin-proteasome system.
            </p>
            <p>
              The key mechanistic insight:{" "}
              <span style={{ color: "var(--text-primary)", fontWeight: 600 }}>
                these proteins retain native-like function; they simply never arrive.
              </span>{" "}
              A small molecule that binds the misfolded intermediate and shifts the folding
              free-energy landscape toward the native basin constitutes a pharmacological chaperone.
              No systematic computational framework for their design has previously been described.
              REFOLD provides this framework.
            </p>
            <p>
              Three FDA-approved pharmacological chaperones currently exist, each discovered by
              brute-force high-throughput screening against a single target at cost exceeding
              $1B per molecule. REFOLD designs them from structural first principles, for every
              protein in the human proteome, fully automatically.
            </p>
          </div>
        </div>

        <div className="space-y-2">
          <div className="section-label">Fig. 1 — Folding energy landscape</div>
          <div className="overflow-hidden border" style={{ borderColor: "var(--border)" }}>
            <Image
              src="/images/cftr_molecule.png"
              alt="3D molecular rendering of a pharmacological chaperone bound in a transient pocket"
              width={600}
              height={450}
              className="w-full h-auto"
              priority
            />
          </div>
          <p className="text-[10px] leading-4" style={{ color: "var(--text-muted)" }}>
            Representative transient pocket (cyan surface) identified in the misfolded intermediate
            of CFTR-F508del. De novo chaperone shown as amber sticks. Generated by REFOLD Stage 2–3.
          </p>
        </div>
      </div>
    </section>
  );
}

// ── Pipeline architecture overview ─────────────────────────────────────────
function PipelineSection() {
  return (
    <section className="border-b" style={{ borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 py-8 space-y-6">

        {/* Architecture overview figure */}
        <div>
          <div className="section-label mb-2">Fig. 2 — REFOLD pipeline overview</div>
          <div className="overflow-hidden border" style={{ borderColor: "var(--border)" }}>
            <Image
              src="/images/arch_chaperone_gap.png"
              alt="The Pharmacological Chaperone Gap and REFOLD Pipeline systemic overview"
              width={1400}
              height={800}
              className="w-full h-auto"
            />
          </div>
          <p className="text-[10px] mt-1 leading-4" style={{ color: "var(--text-muted)" }}>
            Top: Native vs. mutant folding free-energy landscape. Bottom: REFOLD Stage 1→2→3 pipeline producing the proteome-wide chaperone map.
          </p>
        </div>

        {/* Stage table — academic methods-section style */}
        <div>
          <div className="section-label mb-2">Pipeline stages — method summary</div>
          <div className="border" style={{ borderColor: "var(--border)", borderRadius: "2px", overflow: "hidden" }}>
            <table className="w-full border-collapse text-xs">
              <thead>
                <tr style={{ background: "var(--bg-2)", borderBottom: "1px solid var(--border-mid)" }}>
                  {["Stage", "Objective", "Method", "Key Output", "Performance"].map(h => (
                    <th key={h} className="px-4 py-2 text-left font-semibold uppercase tracking-wider"
                        style={{ color: "var(--text-muted)", fontSize: 10 }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {[
                  {
                    stage: "Stage 1", obj: "Rescue amenability filter",
                    method: "GNN-LM Fusion Classifier",
                    output: "Rescue score ∈ [0,1]; threshold ≥ 0.70",
                    perf: "AUC 0.88 (Gaucher), 0.79 (CF)",
                    color: "var(--accent)",
                  },
                  {
                    stage: "Stage 2", obj: "Transient pocket identification",
                    method: "ANM conformational sampling + fpocket α-sphere scoring",
                    output: "Cryptic pocket geometry, E_ij matrix, best conformation PDB",
                    perf: "Druggability ≥ 0.75; absent in WT",
                    color: "var(--violet)",
                  },
                  {
                    stage: "Stage 3", obj: "De novo chaperone design",
                    method: "SE(3)-equivariant diffusion on pocket E_ij conditioning",
                    output: "SMILES, physicochemical properties, composite score",
                    perf: "Score = 0.45·affinity + 0.30·QED + 0.15·SA + 0.10·logP",
                    color: "var(--green)",
                  },
                ].map((s, i) => (
                  <tr key={s.stage}
                      style={{ background: i % 2 === 0 ? "var(--bg)" : "var(--bg-1)", borderBottom: "1px solid var(--border)" }}>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <span className="font-mono font-bold text-[10px]" style={{ color: s.color }}>{s.stage}</span>
                    </td>
                    <td className="px-4 py-3 text-xs" style={{ color: "var(--text-primary)", fontWeight: 500 }}>{s.obj}</td>
                    <td className="px-4 py-3 text-xs" style={{ color: "var(--text-secondary)" }}>{s.method}</td>
                    <td className="px-4 py-3 text-xs font-mono" style={{ color: "var(--text-secondary)" }}>{s.output}</td>
                    <td className="px-4 py-3 text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>{s.perf}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </section>
  );
}

// ── ML architecture diagram ─────────────────────────────────────────────────
function ArchitectureSection() {
  return (
    <section id="methodology" className="border-b" style={{ borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 py-8 space-y-4">

        <div className="grid lg:grid-cols-[200px_1fr] gap-6 items-start">
          <div>
            <div className="section-label mb-2">Fig. 3</div>
            <div className="font-semibold text-sm leading-5" style={{ color: "var(--text-primary)" }}>
              ML Architecture — Technical Detail
            </div>
            <p className="text-xs mt-2 leading-5" style={{ color: "var(--text-secondary)" }}>
              Part A: GNN feature extractor with atom-edge message passing +
              Transformer LM fusion → rescuability logits.
            </p>
            <p className="text-xs mt-1 leading-5" style={{ color: "var(--text-secondary)" }}>
              Part B: SE(3)-equivariant denoising network for structure-conditioned
              molecular generation (T=100→T=1 diffusion trajectory).
            </p>
          </div>
          <div className="space-y-1">
            <GnnDiagram />
            <p className="text-[10px] leading-4" style={{ color: "var(--text-muted)" }}>
              Inputs: AlphaFold2 structure, ESM-2 embeddings (1280-d), FoldX ΔΔG, PSSM conservation scores.
              Conditioning: E_ij Cα–Cα distance matrix from Stage 2 pocket geometry.
            </p>
          </div>
        </div>

        <div className="space-y-1">
          <div className="section-label">Fig. 4 — End-to-end pipeline flow</div>
          <div className="overflow-hidden border" style={{ borderColor: "var(--border)" }}>
            <Image
              src="/images/arch_pipeline_overview.png"
              alt="REFOLD pipeline end-to-end overview"
              width={1400}
              height={700}
              className="w-full h-auto"
            />
          </div>
        </div>
      </div>
    </section>
  );
}

// ── Database preview ────────────────────────────────────────────────────────
function DatabasePreview({ data }: { data: PCDAtlas }) {
  const preview = data.entries.slice(0, 5);
  return (
    <section id="database" className="border-b" style={{ borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 py-8 space-y-4">
        <div className="flex items-end justify-between">
          <div>
            <div className="section-label mb-1">Database Preview</div>
            <h2 className="text-base font-bold" style={{ color: "var(--text-primary)" }}>Chaperone Entries</h2>
            <p className="mt-0.5 text-xs" style={{ color: "var(--text-muted)" }}>
              {data.total_entries.toLocaleString()} entries · sorted by fpocket druggability score (desc.)
            </p>
          </div>
          <Link href="/database"
            className="px-3 py-1.5 text-xs font-semibold border"
            style={{ borderColor: "var(--border-mid)", color: "var(--text-secondary)", borderRadius: "2px" }}>
            Browse all {data.total_entries} entries →
          </Link>
        </div>

        <div className="border" style={{ borderColor: "var(--border)", overflow: "hidden" }}>
          <table className="w-full text-xs border-collapse">
            <thead>
              <tr style={{ background: "var(--bg-2)", borderBottom: "2px solid var(--border-mid)" }}>
                {[
                  { h: "Entry ID", note: "gene · variant" },
                  { h: "Disease", note: "" },
                  { h: "Drug Score", note: "fpocket" },
                  { h: "Chaperone Score", note: "composite" },
                  { h: "MW", note: "Da" },
                  { h: "QED", note: "" },
                ].map(c => (
                  <th key={c.h} className="px-4 py-2 text-left font-semibold"
                      style={{ color: "var(--text-muted)", fontSize: 10 }}>
                    <span className="uppercase tracking-wider">{c.h}</span>
                    {c.note && <span className="font-normal ml-1 normal-case tracking-normal" style={{ color: "var(--border-mid)" }}>({c.note})</span>}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {preview.map((entry, i) => (
                <tr key={entry.entry_id}
                    style={{
                      background: i % 2 === 0 ? "var(--bg)" : "var(--bg-1)",
                      borderBottom: "1px solid var(--border)",
                    }}>
                  <td className="px-4 py-2.5">
                    <Link href={`/database/${entry.entry_id}`} className="block">
                      <div className="flex items-center gap-1.5">
                        <span className="tag tag-cyan">{entry.metadata.gene}</span>
                        <span className="tag tag-amber">{entry.metadata.mutation_mature}</span>
                      </div>
                      <div className="font-mono text-[10px] mt-0.5" style={{ color: "var(--text-muted)" }}>{entry.entry_id}</div>
                    </Link>
                  </td>
                  <td className="px-4 py-2.5">
                    <Link href={`/database/${entry.entry_id}`} className="block text-xs" style={{ color: "var(--text-secondary)" }}>
                      {entry.metadata.disease}
                    </Link>
                  </td>
                  <td className="px-4 py-2.5">
                    <Link href={`/database/${entry.entry_id}`} className="block">
                      <span className="font-mono font-bold text-xs" style={{ color: "var(--accent)" }}>
                        {(entry.pocket.fpocket_druggability ?? 0).toFixed(3)}
                      </span>
                    </Link>
                  </td>
                  <td className="px-4 py-2.5">
                    <Link href={`/database/${entry.entry_id}`} className="block">
                      <span className="font-mono font-bold text-xs" style={{ color: "var(--violet)" }}>
                        {(entry.chaperone?.composite_score ?? 0).toFixed(3)}
                      </span>
                    </Link>
                  </td>
                  <td className="px-4 py-2.5">
                    <Link href={`/database/${entry.entry_id}`} className="block">
                      <span className="font-mono text-xs" style={{ color: "var(--text-secondary)" }}>
                        {(entry.chaperone?.mw ?? 0).toFixed(0)}
                      </span>
                    </Link>
                  </td>
                  <td className="px-4 py-2.5">
                    <Link href={`/database/${entry.entry_id}`} className="block">
                      <span className="font-mono text-xs" style={{ color: "var(--text-secondary)" }}>
                        {(entry.chaperone?.qed ?? 0).toFixed(3)}
                      </span>
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </section>
  );
}

// ── About ────────────────────────────────────────────────────────────────────
function AboutSection() {
  return (
    <section id="about" className="border-b" style={{ borderColor: "var(--border)" }}>
      <div className="max-w-7xl mx-auto px-6 py-8">
        <div className="grid lg:grid-cols-[160px_1fr] gap-10 items-start">

          <div className="space-y-3">
            <div className="overflow-hidden border w-32" style={{ borderColor: "var(--border)" }}>
              <Image
                src="/images/aaryan.jpg"
                alt="Aaryan Senthilvanan"
                width={300}
                height={400}
                className="w-full h-auto"
              />
            </div>
            <div>
              <div className="font-semibold text-xs" style={{ color: "var(--text-primary)" }}>Aaryan Senthilvanan</div>
              <div className="text-[11px] mt-0.5" style={{ color: "var(--text-muted)" }}>Principal Investigator</div>
              <div className="text-[11px] mt-0.5 font-mono" style={{ color: "var(--accent)" }}>S.Y.A.L.I.S Labs</div>
            </div>
          </div>

          <div className="space-y-5">
            <div>
              <div className="section-label mb-1.5">About</div>
              <h2 className="text-base font-bold" style={{ color: "var(--text-primary)" }}>
                REFOLD — Proteome-Scale Pharmacological Chaperone Design
              </h2>
            </div>

            <div className="space-y-3 text-xs leading-6" style={{ color: "var(--text-secondary)" }}>
              <p>
                REFOLD is a fully automated, end-to-end computational pipeline that accepts any
                human disease-associated missense mutation as input and produces: (1) a binary
                prediction of whether the variant drives pathogenesis via protein misfolding
                rather than active-site disruption; (2) the 3D transient-conformation structure
                of the mutant protein with cryptic binding pockets resolved; (3) de novo designed
                small-molecule candidates that bind those pockets and thermodynamically stabilize
                the native fold.
              </p>
              <p>
                The PCD is the product of continuously running REFOLD across the complete human
                proteome — processing every pathogenic missense variant in ClinVar sequentially,
                with each result automatically injected into this living database.
              </p>
            </div>

            <div className="border" style={{ borderColor: "var(--border)", borderRadius: "2px", overflow: "hidden" }}>
              <table className="w-full text-xs border-collapse">
                <tbody>
                  {[
                    ["Human protein-coding genes", "20,430"],
                    ["ClinVar pathogenic missense variants", "178,597"],
                    ["Genes with known pathogenic variants", "5,992"],
                    ["Pipeline runtime per variant (avg.)", "~4–8 min"],
                    ["Database update frequency", "Continuous (daemon)"],
                  ].map(([label, val], i) => (
                    <tr key={label}
                        style={{ background: i % 2 === 0 ? "var(--bg)" : "var(--bg-1)", borderBottom: "1px solid var(--border)" }}>
                      <td className="px-4 py-2" style={{ color: "var(--text-secondary)" }}>{label}</td>
                      <td className="px-4 py-2 font-mono font-semibold text-right" style={{ color: "var(--accent)" }}>{val}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ── Footer ───────────────────────────────────────────────────────────────────
function Footer({ data }: { data: PCDAtlas }) {
  return (
    <footer className="border-t py-4" style={{ borderColor: "var(--border)", background: "var(--bg-1)" }}>
      <div className="max-w-7xl mx-auto px-6 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-2">
        <div className="text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>
          <span style={{ color: "var(--accent)", fontWeight: 700 }}>PCD</span>
          {" "}v{data.version} · S.Y.A.L.I.S Labs · Powered by REFOLD
        </div>
        <div className="text-[11px] font-mono" style={{ color: "var(--text-muted)" }}>
          {data.total_entries.toLocaleString()} entries · build {data.build_date} · continuous update
        </div>
      </div>
    </footer>
  );
}

// ── Page ───────────────────────────────────────────────────────────────────
export default async function HomePage() {
  const data = await fetchAtlas();

  return (
    <div style={{ background: "var(--bg)", minHeight: "100vh" }}>
      <NavBar />
      <div style={{ paddingTop: "40px" }}>
        <IdentityHeader data={data} />
        <BackgroundSection />
        <PipelineSection />
        <ArchitectureSection />
        <DatabasePreview data={data} />
        <AboutSection />
        <Footer data={data} />
      </div>
    </div>
  );
}
