"""Post-processing: convert raw 3D atom cloud to valid SMILES."""

from __future__ import annotations

import logging
import subprocess
import tempfile
from pathlib import Path
from typing import Optional

import numpy as np

from refold.constants import MOL_ATOM_TYPES

logger = logging.getLogger(__name__)


def atoms_to_xyz_block(
    atom_positions: np.ndarray,
    atom_types: np.ndarray,
    atom_type_names: list[str] = MOL_ATOM_TYPES,
) -> str:
    """
    Convert atom positions [N, 3] and type indices [N] to XYZ format string.
    """
    n = len(atom_positions)
    lines = [str(n), "Generated by REFOLD diffusion"]
    for i in range(n):
        elem = atom_type_names[int(atom_types[i])] if int(atom_types[i]) < len(atom_type_names) else "C"
        x, y, z = atom_positions[i]
        lines.append(f"{elem}  {x:.4f}  {y:.4f}  {z:.4f}")
    return "\n".join(lines)


def xyz_to_smiles_obabel(xyz_block: str) -> Optional[str]:
    """Convert XYZ text to SMILES using Open Babel subprocess."""
    try:
        result = subprocess.run(
            ["obabel", "-ixyz", "-osmi", "--gen3d"],
            input=xyz_block,
            capture_output=True,
            text=True,
            timeout=10,
        )
        smiles = result.stdout.strip().split()[0] if result.stdout.strip() else None
        return smiles
    except (subprocess.TimeoutExpired, FileNotFoundError, IndexError) as e:
        logger.debug(f"obabel conversion failed: {e}")
        return None


def xyz_to_smiles_rdkit(xyz_block: str) -> Optional[str]:
    """Convert XYZ text to SMILES using RDKit (fallback)."""
    try:
        from rdkit import Chem
        from rdkit.Chem import AllChem

        with tempfile.NamedTemporaryFile(mode="w", suffix=".xyz", delete=False) as f:
            f.write(xyz_block)
            xyz_path = f.name

        try:
            mol = Chem.MolFromXYZFile(xyz_path)
            if mol is None:
                return None
            Chem.SanitizeMol(mol)
            return Chem.MolToSmiles(mol)
        finally:
            Path(xyz_path).unlink(missing_ok=True)
    except Exception as e:
        logger.debug(f"RDKit XYZ conversion failed: {e}")
        return None


def decode_molecule(
    atom_positions: np.ndarray,
    atom_types: np.ndarray,
    atom_type_names: list[str] = MOL_ATOM_TYPES,
) -> Optional[str]:
    """
    Convert diffusion model output to SMILES.

    Tries Open Babel first, falls back to RDKit.
    """
    xyz = atoms_to_xyz_block(atom_positions, atom_types, atom_type_names)

    smiles = xyz_to_smiles_obabel(xyz)
    if smiles and len(smiles) > 2:
        return smiles

    smiles = xyz_to_smiles_rdkit(xyz)
    return smiles


def sanitize_and_canonicalize(smiles: str) -> Optional[str]:
    """Return canonical SMILES or None if invalid."""
    try:
        from rdkit import Chem
        mol = Chem.MolFromSmiles(smiles)
        if mol is None:
            return None
        return Chem.MolToSmiles(mol)
    except Exception:
        return None
